services:
  nginx:
    image: nginx
    ports:
      - 100:80
    networks:
      - nw1
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.75' # 75%
          memory: 100MB
networks:
  nw1:
