name: my-app

services:
  web:
    image: nginx:latest
    ports:
      - "1090:80"
      - "78:80"
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - my-webnet
  web1:
    image: nginx:latest
    ports:
      - "1080:80"
      - "1070:80"
    volumes:
      - ./web1:/usr/share/nginx/html
    networks:
      - my-webnet

networks:
  my-webnet: