version: '3.1'
services:
  oracle:
    image: doctorkirk/oracle-19c
    container_name: oracle_db
    restart: always
    ports:
      - "1521:1521"
    volumes:
      - "oracle_db:/opt/oracle/oradata"
    environment:
      ORACLE_SID: 'ORCLCDB'
      ORACLE_PDB: 'ORCLPDB1'
      ORACLE_PWD: 'oracle'
volumes:
  oracle_db:
