version: '3.8'

services:
  client:
    image: alpine
    command: sleep 1000
    networks:
      - client_server_nw
  
  server:
    image: alpine
    command: ping 8.8.8.8
    networks:
      - client_server_nw
      - server_db_nw

  my-db:
    image: postgres
    environment:
      POSTGRES_USER: vanle96
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: userDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - server_db_nw
    ports:
      - 5432:5432

networks:
  client_server_nw:
  server_db_nw:

volumes:
  postgres-data:
    driver: local
