version: '3.8'

services:
  node:
    image: my-node-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: vanle
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: myDb
    ports:
      - 5000:3000
    networks:
      - node_mysql_nw
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: myDb
      MYSQL_USER: vanle
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - node_mysql_nw

networks:
  node_mysql_nw:
