version: '3.9'

services:
  client:
    image: nginx
    command: tail -f /dev/null
    networks:
      - fe_nw
  server:
    image: ubuntu
    command: tail -f /dev/null
    networks:
      - fe_nw
      - be_nw
    depends_on:
      - database
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: myDb
      MYSQL_USER: vanle
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
    networks:
      - be_nw
networks:
  fe_nw:
  be_nw: