version: '3.8'

services:
  client:
    image: alpine
    command: sleep 1000
    networks:
      - client_server_nw
  
  server:
    image: alpine
    command: ping 8.8.8.8
    networks:
      - client_server_nw
      - server_db_nw

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: myDb
      MYSQL_USER: vanle
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - server_db_nw

networks:
  client_server_nw:
  server_db_nw:

volumes:
  mysql-data:
    driver: local
