version: '3.8'

services:
  web:
    image: nginx
    ports:
      - 81:80
      - 82:80
    command: tail -f /dev/null
    networks:
      - fe_nw
  app:
    build:
      context: ./node-api-docker
      dockerfile: ./Dockerfile
    ports:
      - 83:8080
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: vanle
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: myDb
    networks:
      - fe_nw
      - be_nw
    depends_on:
      - database
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: myDb
      MYSQL_USER: vanle
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
    networks:
      - be_nw
    volumes:
      - mysql:/var/lib/mysql
networks:
  fe_nw:
  be_nw:
volumes:
  mysql:
