version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 83:8080
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: vanle
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: myDb
    networks:
      - be_nw
    depends_on:
      - database
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: myDb
      MYSQL_USER: vanle
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
    networks:
      - be_nw
    volumes:
      - mysql:/var/lib/mysql
networks:
  be_nw:
volumes:
  mysql: